iso-date and higher resilience
Thynix/pyProbe pull request #1
Opened 2018-01-27 21:52 UTC by ArneBab

2018-04-08 03:53 UTC, Thynix requested changes

2018-04-08 03:53 UTC, Thynix commented on mdx_generateddate.py
>  # Ex: "September 02, 2012"
This comment should reflect the change as well.

2018-04-08 03:53 UTC, Thynix commented on probe.py
> +        probe_type_code = getattr(probeTypes, probe_type).index
Hm? Under what circumstances does this happen? What are the effects - does it crash entirely?

2018-05-11 20:02 UTC, ArneBab commented on probe.py
> +        probe_type_code = getattr(probeTypes, probe_type).index
IIRC it stopped providing results. But memory is hazy …

2018-05-11 20:02 UTC, ArneBab commented on mdx_generateddate.py
>  # Ex: "September 02, 2012"
Ah, yes …

2018-10-27 08:20 UTC, ArneBab commented
This pull-request now also holds my fixes for using enum34 … would be great if you could pull it!

2018-11-17 17:51 UTC, Thynix requested changes
Sorry for the delay!

2018-11-17 17:51 UTC, Thynix commented on fnprobe/db.py
> +    DISCONNECTED=1
It looks like the error codes [start at 0](https://github.com/freenet/fred/blob/build01482/src/freenet/node/probe/Error.java#L7) and `DISCONNECTED((byte) 0),` Am I missing something?

2018-11-17 17:51 UTC, Thynix commented on fnprobe/db.py
> +    BANDWIDTH=1
Probe types [also start at 0](https://github.com/freenet/fred/blob/build01482/src/freenet/node/probe/Type.java#L7)

2018-11-17 17:53 UTC, Thynix commented on probe.py
> +        probe_type_code = getattr(probeTypes, probe_type).value
My assumption is this change was necessary because the enum values were wrong?

2018-11-17 18:43 UTC, ArneBab commented on probe.py
> +        probe_type_code = getattr(probeTypes, probe_type).value
yes, and types are added in the configuration where they aren’t validated, so the error only turns up here.

2018-11-17 18:49 UTC, ArneBab commented on fnprobe/db.py
> +    DISCONNECTED=1
yes, it seems that for enum types the numbers can be anything, not just 0-N or 1-N. Which is somewhat strange … 

so this might just be wrong. Thank you for catching it!

2018-11-17 18:49 UTC, ArneBab commented on fnprobe/db.py
> +    DISCONNECTED=1
yikes! likely I got it wrong …

2018-11-17 19:36 UTC, Thynix commented on probe.py
> +        probe_type_code = getattr(probeTypes, probe_type).value
Logging it as an error seems reasonable in any case.

2019-01-23 00:08 UTC, merged